# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: al-mosquito-id
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pytest
  - sphinx
  - matplotlib
  - pip
  - pip:
    - tensorflow>=1.5
    - pillow==5.1.0
    - requests==2.18.4
    - numpy>=1.14.5
    - scikit-learn==0.19.2
    - scikit-video==1.1.10
    - click<7,>=6.7
    - natsort==6.2.0
    - opencv-python==4.1.0.25
    - scipy==1.2.1
    - natsort==6.0.0
    - matplotlib==3.0.3
    - itkwidgets==0.14.0
    - pandas<0.21
    - git+https://github.com/czbiohub/luminoth-uv-imaging.git@master#egg=luminoth-uv-imaging 
