# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-kmermaid-1.0.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # TODO nf-core: Add required software dependencies here
  - bioconda::sourmash=3.5.0
  - bioconda::samtools=1.10
  - bioconda::screed=1.0.4
  - conda-forge::tqdm=4.43.0
  - bioconda::khmer=3.0.0a3
  - anaconda::gcc_linux-64 # Required for bam2fasta and pysam
  - anaconda::make # Required for bam2fasta and pysam
  - alabaster=0.7.12
  - fastp=0.20.0
  - fastqc=0.11.9
  - matplotlib=3.1.1 # don't upgrade, multiqc conflict
  - multiqc=1.8
  - numpy=1.17.5
  - pathos=0.2.5
  - bioconda::pysam=0.16.0
  - pip=20.0.2
  - pytest=5.3.4
  - seqtk=1.3
  - ska=1.0
  - sphinx=2.3.1
  - jupyter=1.0.0
  - conda-forge::s3fs=0.4.2
  - sortmerna=2.1b # for metatranscriptomics
  - pip:
    - bam2fasta==1.0.7
    - sencha==1.0.0 # need to release a new version and change this
